/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register/buyer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new buyer account */
        post: operations["registerBuyer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/seller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new seller account and initiate Stripe Connect onboarding
         * @description Creates a seller-role user, creates a Stripe Connect Express account, and
         *     returns a one-time onboarding URL. The client must redirect the seller to
         *     `connectOnboardingUrl`. The seller cannot publish products until onboarding
         *     is complete.
         */
        post: operations["registerSeller"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Verifies credentials and sets an `auth_token` httpOnly cookie on success.
         *     The token is never present in the response body.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the auth_token cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a password reset email
         * @description Always returns 204 regardless of whether the email is registered,
         *     to avoid leaking account existence.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password using a one-time reset token */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update display name or email (requires current password) */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all product categories
         * @description Returns the complete seeded category list. No auth required.
         */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse published products with optional search and category filter
         * @description Returns published products only. Full-text search is ranked by PostgreSQL
         *     `ts_rank`; category filter is applied as an AND condition with search.
         *     Cursor-based pagination; default page size 20.
         */
        get: operations["listProducts"];
        put?: never;
        /** Create a new product listing (seller only, starts unpublished) */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a product by ID
         * @description Returns published products to all callers. The owning seller and admins
         *     can also retrieve unpublished products. Returns 404 when the product is
         *     unpublished and the caller is neither owner nor admin.
         */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        /** Permanently delete a product (admin only) */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        /** Update product fields (owning seller only) */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/products/{id}/published": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Publish or unpublish a product (owning seller or admin)
         * @description Before publishing, validates: imageUrl is set, priceCents > 0, and
         *     (for seller callers) Stripe Connect onboarding is complete.
         */
        patch: operations["setProductPublished"];
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated buyer's current cart
         * @description Returns an empty cart (items=[], sellerId=null, totalCents=0) if no
         *     items have been added. Never returns 404.
         */
        get: operations["getCart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a product to the cart (or increment quantity if already present)
         * @description Enforces the single-seller constraint — a 409 is returned if the cart
         *     already contains items from a different seller. Also returns 409 if
         *     the product is out of stock.
         */
        post: operations["addCartItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a product from the cart */
        delete: operations["removeCartItem"];
        options?: never;
        head?: never;
        /** Update the quantity of a line item */
        patch: operations["updateCartItem"];
        trace?: never;
    };
    "/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Stripe Payment Intent for the current cart
         * @description Validates the cart (non-empty, seller onboarded) and shipping address, then
         *     creates a Stripe Payment Intent. Returns `clientSecret` for Stripe.js to
         *     complete the payment client-side. **The server never accepts a price from
         *     the client** — totalCents always comes from the cart.
         */
        post: operations["initiateCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stripe/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Stripe webhook events
         * @description Verifies the `Stripe-Signature` header and processes
         *     `payment_intent.succeeded` events idempotently. All events return 200
         *     (including already-processed events) to prevent Stripe retries. Only
         *     signature verification failures return 400.
         */
        post: operations["handleStripeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated buyer's orders (sorted newest first) */
        get: operations["listMyOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full order detail
         * @description Access is scoped by role:
         *     - **Buyer**: only their own orders.
         *     - **Seller**: only orders containing their products; line items scoped to their products.
         *     - **Admin**: unrestricted.
         *
         *     Returns 404 when the order does not exist or the caller is not authorised.
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all products owned by the authenticated seller (including unpublished) */
        get: operations["listSellerProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders containing the authenticated seller's products */
        get: operations["listSellerOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/ship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark an order as shipped (owning seller only)
         * @description Transitions status from `paid` → `shipped`. Returns 409 if the current
         *     status is not `paid`. Optionally records a tracking number (max 100 chars).
         */
        patch: operations["markOrderShipped"];
        trace?: never;
    };
    "/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all products across all sellers with search and status filter (admin only) */
        get: operations["adminListProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all orders across all buyers and sellers (admin only) */
        get: operations["adminListOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all registered users with role and registration date (admin only) */
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Amount in integer cents (never floats). Use minimum:1 for prices.
         * @example 4999
         */
        Money: number;
        /** @description Opaque base64 cursor for keyset pagination. */
        Cursor: string;
        /** @enum {string} */
        Role: "buyer" | "seller" | "admin";
        /** @enum {string} */
        OrderStatus: "pending_payment" | "paid" | "shipped" | "delivered" | "cancelled";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            role: components["schemas"]["Role"];
            /** @description Stripe Connect Express account ID. Only set for sellers. */
            stripeAccountId?: string | null;
            stripeOnboardingDone: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        Category: {
            id: string;
            name: string;
            slug: string;
        };
        Product: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sellerId: string;
            categoryId: string;
            title: string;
            description: string;
            /** @description Product price in integer cents */
            priceCents: number;
            /** @description Flat shipping cost in integer cents */
            shippingCents: number;
            stockQuantity: number;
            /** Format: uri */
            imageUrl: string;
            published: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ShippingAddress: {
            name: string;
            line1: string;
            city: string;
            state: string;
            postal: string;
            /** @description ISO 3166-1 alpha-2 country code (e.g. "US", "GB") */
            country: string;
        };
        CartLineItem: {
            /** Format: uuid */
            productId: string;
            productTitle: string;
            quantity: number;
            /** @description Price at time the item was added (snapshot, never updated) */
            snapshotPriceCents: number;
            /** @description Current shipping cost for this product */
            shippingCents: number;
            /** @description (snapshotPriceCents + shippingCents) × quantity — computed server-side */
            lineTotalCents: number;
        };
        Cart: {
            /** Format: uuid */
            userId: string;
            /**
             * Format: uuid
             * @description Seller whose products are in the cart. null when cart is empty.
             */
            sellerId?: string | null;
            items: components["schemas"]["CartLineItem"][];
            /** @description Sum of all lineTotalCents — computed server-side on every read */
            totalCents: number;
        };
        OrderItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            /** Format: uuid */
            productId: string;
            quantity: number;
            /** @description Price per unit in integer cents at time of order */
            unitPriceCents: number;
        };
        Order: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            buyerId: string;
            /** Format: uuid */
            sellerId: string;
            status: components["schemas"]["OrderStatus"];
            /** @description Authoritative total in integer cents, set at order creation */
            totalCents: number;
            shippingAddress: components["schemas"]["ShippingAddress"];
            stripePaymentIntentId: string;
            trackingNumber?: string | null;
            items: components["schemas"]["OrderItem"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Lightweight order representation used in list responses */
        OrderSummary: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["OrderStatus"];
            totalCents: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description User as seen by admins — no passwordHash */
        AdminUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description RFC 7807 Problem Details object. Returned with Content-Type
         *     `application/problem+json` on all 4xx and 5xx responses.
         *     The `type` URI is a stable machine-readable error code clients
         *     can branch on without parsing `detail` strings (see ADR-0004).
         */
        ProblemDetails: {
            /**
             * @description URI identifying the problem type. Follows the pattern
             *     `urn:marketplace:error:<code>`.
             * @example urn:marketplace:error:conflict
             */
            type: string;
            /**
             * @description Human-readable summary of the problem type (stable per type URI)
             * @example Conflict
             */
            title: string;
            /**
             * @description The HTTP status code for this occurrence
             * @example 409
             */
            status: number;
            /**
             * @description Human-readable explanation for this specific occurrence
             * @example That email address is already registered.
             */
            detail: string;
        };
    };
    responses: {
        /** @description Missing or invalid auth_token cookie */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:marketplace:error:unauthorized",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "detail": "Authentication is required. Please log in."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but insufficient role for this operation */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:marketplace:error:forbidden",
                 *       "title": "Forbidden",
                 *       "status": 403,
                 *       "detail": "You do not have permission to perform this action."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource not found or not accessible to the caller */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:marketplace:error:not-found",
                 *       "title": "Not Found",
                 *       "status": 404,
                 *       "detail": "The requested resource does not exist."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Conflict with current resource state (e.g. duplicate email) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:marketplace:error:conflict",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "detail": "That email address is already registered."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request body failed validation */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:marketplace:error:validation",
                 *       "title": "Unprocessable Entity",
                 *       "status": 422,
                 *       "detail": "priceCents must be a positive integer."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Bad request (e.g. expired or already-used token) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:marketplace:error:invalid-token",
                 *       "title": "Bad Request",
                 *       "status": 400,
                 *       "detail": "The password reset token is expired or has already been used."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Pagination cursor returned as nextCursor in a previous response */
        cursor: components["schemas"]["Cursor"];
        /** @description Maximum items to return (default 20, max 100) */
        limit: number;
        productId: string;
        orderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerBuyer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    displayName: string;
                };
            };
        };
        responses: {
            /** @description Buyer registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    registerSeller: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    displayName: string;
                };
            };
        };
        responses: {
            /** @description Seller registered; redirect to connectOnboardingUrl */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                        /**
                         * Format: uri
                         * @description Stripe Connect Express onboarding redirect URL
                         */
                        connectOnboardingUrl: string;
                    };
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful; auth_token cookie is set */
            200: {
                headers: {
                    /** @description httpOnly Secure SameSite=Strict auth_token cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out; auth_token cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Reset email dispatched (if an account with that email exists) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The reset token delivered via email */
                    token: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Password updated; token is now invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user's profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName?: string;
                    /** Format: email */
                    email?: string;
                    /** @description Current password required for any profile change */
                    currentPassword: string;
                };
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: {
                /** @description Full-text search term */
                q?: string;
                /** @description Filter by category ID */
                categoryId?: string;
                /** @description Pagination cursor returned as nextCursor in a previous response */
                cursor?: components["parameters"]["cursor"];
                /** @description Maximum items to return (default 20, max 100) */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of published products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Product"][];
                        nextCursor?: components["schemas"]["Cursor"];
                    };
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    description: string;
                    /** @description Product price in integer cents */
                    priceCents: number;
                    /** @description Flat shipping cost in integer cents */
                    shippingCents: number;
                    categoryId: string;
                    stockQuantity: number;
                    /** Format: uri */
                    imageUrl: string;
                };
            };
        };
        responses: {
            /** @description Product created in unpublished state */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product permanently deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    description?: string;
                    priceCents?: number;
                    shippingCents?: number;
                    categoryId?: string;
                    stockQuantity?: number;
                    /** Format: uri */
                    imageUrl?: string;
                };
            };
        };
        responses: {
            /** @description Product updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    setProductPublished: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    published: boolean;
                };
            };
        };
        responses: {
            /** @description Product publish state updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current cart state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    productId: string;
                    quantity: number;
                };
            };
        };
        responses: {
            /** @description Cart after the item was added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description Product out of stock (`urn:marketplace:error:conflict`) or cart already
             *     contains items from a different seller.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    removeCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart after the item was removed (may now be empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    quantity: number;
                };
            };
        };
        responses: {
            /** @description Cart after the quantity was updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    initiateCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    shippingAddress: components["schemas"]["ShippingAddress"];
                };
            };
        };
        responses: {
            /** @description Payment Intent created; use clientSecret with Stripe.js */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Stripe Payment Intent client secret for Stripe.js */
                        clientSecret: string;
                        /** @description Stripe Payment Intent ID stored for idempotency */
                        paymentIntentId: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    handleStripeWebhook: {
        parameters: {
            query?: never;
            header: {
                /** @description HMAC signature header from Stripe for payload verification */
                "Stripe-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Event acknowledged (processed or already seen — idempotent) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Webhook signature verification failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "urn:marketplace:error:webhook-signature",
                     *       "title": "Bad Request",
                     *       "status": 400,
                     *       "detail": "Webhook signature verification failed."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listMyOrders: {
        parameters: {
            query?: {
                /** @description Pagination cursor returned as nextCursor in a previous response */
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated order list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OrderSummary"][];
                        nextCursor?: components["schemas"]["Cursor"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["orderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full order detail including line items and shipping address */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSellerProducts: {
        parameters: {
            query?: {
                /** @description Pagination cursor returned as nextCursor in a previous response */
                cursor?: components["parameters"]["cursor"];
                /** @description Maximum items to return (default 20, max 100) */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of this seller's products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Product"][];
                        nextCursor?: components["schemas"]["Cursor"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listSellerOrders: {
        parameters: {
            query?: {
                /** @description Pagination cursor returned as nextCursor in a previous response */
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of orders for this seller (sorted newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OrderSummary"][];
                        nextCursor?: components["schemas"]["Cursor"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    markOrderShipped: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["orderId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    trackingNumber?: string;
                };
            };
        };
        responses: {
            /** @description Order status transitioned to shipped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    adminListProducts: {
        parameters: {
            query?: {
                /** @description Search by product title */
                q?: string;
                /** @description Filter by publish status */
                status?: "all" | "published" | "unpublished";
                /** @description Pagination cursor returned as nextCursor in a previous response */
                cursor?: components["parameters"]["cursor"];
                /** @description Maximum items to return (default 20, max 100) */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of all products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Product"][];
                        nextCursor?: components["schemas"]["Cursor"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminListOrders: {
        parameters: {
            query?: {
                /** @description Pagination cursor returned as nextCursor in a previous response */
                cursor?: components["parameters"]["cursor"];
                /** @description Maximum items to return (default 20, max 100) */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of all orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OrderSummary"][];
                        nextCursor?: components["schemas"]["Cursor"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                /** @description Pagination cursor returned as nextCursor in a previous response */
                cursor?: components["parameters"]["cursor"];
                /** @description Maximum items to return (default 20, max 100) */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of all users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminUser"][];
                        nextCursor?: components["schemas"]["Cursor"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
